CREATE TABLE IF NOT EXISTS PROPERTIES (
  KEY         VARCHAR(2048),
  VALUE       VARCHAR(4096),
  APPLICATION VARCHAR(128),
  PROFILE     VARCHAR(128),
  LABEL       VARCHAR(128),
  PRIMARY KEY (`KEY`, `APPLICATION`, `PROFILE`, `LABEL`)
);


INSERT INTO PROPERTIES (APPLICATION, PROFILE, LABEL, KEY, VALUE) VALUES ('A1', 'local', 'develop', 'a1k1', '로컬 값');
INSERT INTO PROPERTIES (APPLICATION, PROFILE, LABEL, KEY, VALUE) VALUES ('A1', 'local', 'develop', 'a1k2', '로컬 값');
INSERT INTO PROPERTIES (APPLICATION, PROFILE, LABEL, KEY, VALUE) VALUES ('A1', 'local', 'develop', 'a1k3', '로컬 값');
INSERT INTO PROPERTIES (APPLICATION, PROFILE, LABEL, KEY, VALUE) VALUES ('A1', 'dev', 'develop', 'a1name', '개발 값');
INSERT INTO PROPERTIES (APPLICATION, PROFILE, LABEL, KEY, VALUE) VALUES ('A1', 'stage', 'master', 'a1name', '스테이징 값');
INSERT INTO PROPERTIES (APPLICATION, PROFILE, LABEL, KEY, VALUE) VALUES ('A1', 'prod', 'master', 'a1name', '운영 값');

INSERT INTO PROPERTIES (APPLICATION, PROFILE, LABEL, KEY, VALUE) VALUES ('A2', 'local', 'develop', 'a2k1', '로컬 값');
INSERT INTO PROPERTIES (APPLICATION, PROFILE, LABEL, KEY, VALUE) VALUES ('A2', 'local', 'develop', 'a2k2', '로컬 값');
INSERT INTO PROPERTIES (APPLICATION, PROFILE, LABEL, KEY, VALUE) VALUES ('A2', 'local', 'develop', 'a2k3', '로컬 값');
INSERT INTO PROPERTIES (APPLICATION, PROFILE, LABEL, KEY, VALUE) VALUES ('A2', 'dev', 'develop', 'a2name', '개발 값');
INSERT INTO PROPERTIES (APPLICATION, PROFILE, LABEL, KEY, VALUE) VALUES ('A2', 'stage', 'master', 'a2name', '스테이징 값');
INSERT INTO PROPERTIES (APPLICATION, PROFILE, LABEL, KEY, VALUE) VALUES ('A2', 'prod', 'master', 'a2name', '운영 값');