name: Publish Docker image

#on:
#  release:
#    types: [published]

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Gradlew jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Login to Docker Repo
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REPO_USERNAME }}
          password: ${{ secrets.DOCKER_REPO_PASSWORD }}
          registry: ghcr.io

      - name: Push to Docker Repo
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/deuxksy/zzizily-spring-cloud-config-server/zzizily-spring-cloud-config-server
