name: Publish Docker image

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_REPO_USERNAME }}
          password: ${{ secrets.DOCKER_REPO_PASSWORD }}
          repository: cromksy/zzizily-spring-cloud-config-server
          tag_with_ref: true