name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  build:
    name: Gradlew build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew jar

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_REPO_USERNAME }}
          password: ${{ secrets.DOCKER_REPO_PASSWORD }}
          registry: ghcr.io
          repository: deuxksy/zzizily-spring-cloud-config-server/zzizily-spring-cloud-config-server
          tag_with_ref: true